### ISSUE TITLE
Setup a CI pipeline 

### ISSUE THREAD

**Issue by Gifflen** [checkmate/simpl#45]

**Comment by samstav** [comment]
We have PRs setup to test in travis. Should we switch to using CircleCI?

**Comment by ziadsawalha** [comment]
Do we need that for simpl? Does CircleCI have a free tier?

**Comment by Gifflen** [comment]
They do, We could switch to that if needed. Since it is already up and working in Travis I think thats fine. Travis plays just as well with coveralls so I don't see a specific reason to move to circle at the moment. The only case I could make would be to have a parallel with with some of our other projects in terms of pipeline.
